### ISSUE TITLE
Hot water control

### ISSUE THREAD

**Issue by adavison007** [SeydX/homebridge-tado-platform#21]
Ok, so now the hot water switch is working, can you make the auto work like it does for heating? I.e. when I turn off hot water I’d like it to update on new to auto change set in the Tado app... currently it stays of until changed/..

**Comment by SeydX** [comment]
@adavison007 

the overrideFunction is already implemented.. which Accessory type u re using for hotwater? thermostat or faucet?

**Comment by adavison007** [comment]
It's the hot water on off button... I have it set to Auto in JSON but it sets to manual in tado, the Thermostats all work and go to auto perfectly.

**Comment by omarassil** [comment]
I just came across this issue. I have exactly the same. the HOT_WATER (type boiler) only works on manual override option. I love the plugin because Tado doesn't expose hot_water to Homekit (it only exposes the thermostats) so would love to be able to turn hot water on from Homekit but not worry about it staying on forever

**Comment by mpjalexander** [comment]
Hi @SeydX, would it also be possible to add a third option for all device types of a timer, like you can in the Tado app? For example, allow "overrideMode": "timer". You'd also need to be able to specify the duration of the timer, either somehow via the existing overrideMode setting, or some new "overrideTimer" setting. Does the Tado API allow for that?

**Comment by SeydX** [comment]
Added/Fixed in v6
